name: Generate routes

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  pull-requests: write
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          ref: 'main'

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Install Code Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --use-pep517 -r requirements.txt

      - name: Run generator script
        run: python generate.py

      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: Update routes
          sign-commits: true
          base: main
          branch: bot/update-routes
          delete-branch: true
          title: Update routes
          body: Update generated routes config file
          add-paths: openvpn/routes.conf
