name: Generate routes

on:
  push:
    branches:
      - master

permissions:
  pull-requests: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: 'master'

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Code Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run generator script
        run: python generate.py

      - name: Create pull request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Update routes
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          base: master
          branch: bot/update-routes
          delete-branch: true
          title: Update routes
          body: Update generated routes config file
          add-paths: openvpn/routes.conf
